In [1]:
my_list=[1 , 2, 3]

In [2]:
import numpy as np

In [3]:
arr= np.array(my_list)

In [4]:
arr


array([1, 2, 3])

In [5]:
myth =[ [1 , 3 , 4],[4,5,7],[6,7,8]]

In [6]:
np.array(myth)

array([[1, 3, 4],
       [4, 5, 7],
       [6, 7, 8]])

In [13]:
np.arange(0 ,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [18]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
np.linspace(1,2,3)

array([ 1. ,  1.5,  2. ])

In [25]:
np.eye(3,3,4)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
np.random.rand(11)

array([ 0.27251265,  0.08234486,  0.34771443,  0.52337013,  0.5890865 ,
        0.2289815 ,  0.0794811 ,  0.70071451,  0.39871745,  0.97140724,
        0.38418525])

In [29]:
np.random.rand(4,4)

array([[ 0.14986608,  0.46519129,  0.88061315,  0.15445939],
       [ 0.71422694,  0.45562445,  0.96097402,  0.97306572],
       [ 0.71861993,  0.69120955,  0.60187236,  0.9931584 ],
       [ 0.84163098,  0.61340589,  0.14094797,  0.27857788]])

In [44]:
a=np.random.randint(1,100,19)

In [45]:
a

array([92, 46, 23, 65, 76,  8, 11, 21, 90, 94, 75, 41,  8, 60, 71, 57, 56,
       35, 58])

In [35]:
a

array([ 8, 76, 79, 33, 37, 56, 65, 67, 29, 13, 19, 86, 16, 15,  2, 62, 53,
       56, 74, 82, 51, 87, 73, 69, 73, 64, 87,  4, 52,  7, 26,  7,  8, 82,
       80, 12, 64, 53,  8, 64, 24, 54, 70, 16, 27, 62, 24, 88,  2, 20, 94,
       97, 99, 26, 28, 90, 89, 84, 76, 87, 44, 79, 37, 77, 72, 70, 11, 33,
       40, 10, 81, 41, 51, 27, 33, 92, 76, 68, 92, 64, 40, 33, 84, 39, 82,
       19, 32, 17, 90, 47, 96, 75, 83, 58, 34, 85, 57, 43, 91, 84, 26,  6,
       27, 13, 89, 71, 97, 69, 70, 52, 97, 15, 50, 98, 94, 23, 63, 92, 76,
        7, 46, 82, 72, 28,  1, 13, 94, 79, 64, 29, 13,  2, 81, 94, 13, 58,
        3,  6, 80, 21, 36, 85, 47, 64, 25, 22, 94, 29, 32, 78,  9, 40,  7,
        3, 78, 48, 75, 44, 75,  8, 50,  4, 60, 84, 28, 56, 60, 69, 74, 40,
       18,  7, 55, 95, 71, 15, 94, 11, 59, 16, 43, 18, 33, 84, 97, 50, 75,
       96, 82, 47,  5, 28,  1, 61, 30, 79, 18, 94, 34])

In [38]:
a.reshape(199,199)

ValueError: cannot reshape array of size 199 into shape (199,199)

In [41]:
a.argmax()

52

In [42]:
a.argmin()

124

In [46]:
a.shape

(19L,)

In [47]:
a.reshape(5,5)

ValueError: cannot reshape array of size 19 into shape (5,5)

In [1]:
help(l.count)

NameError: name 'l' is not defined